#Amazon-Books-Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: amazon-books-service
spec:
  type: LoadBalancer
  selector:
    app: amazon-books
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 80  # Port inside the Pod
